# Generated by Django 5.2.5 on 2025-11-04 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipamentos",
            fields=[
                ("unique_id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
                ("tensao", models.DecimalField(decimal_places=2, max_digits=10)),
                ("peso_u", models.DecimalField(decimal_places=2, max_digits=10)),
                ("altura_u", models.DecimalField(decimal_places=2, max_digits=10)),
                ("largura_u", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "profundidade_u",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "resolucao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("armazenamento", models.IntegerField(blank=True, null=True)),
                ("conectividade", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tipos",
            fields=[
                ("unique_id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Movimentacoes",
            fields=[
                ("unique_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantidade", models.IntegerField()),
                ("data", models.DateField()),
                ("fornecedor", models.CharField(max_length=100)),
                ("lote", models.CharField(max_length=50)),
                (
                    "tipo_operacao",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=20,
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.equipamentos",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="equipamentos",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="estoque.tipos"
            ),
        ),
    ]
