# Generated by Django 5.2.7 on 2025-11-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
